### ISSUE TITLE
Inventory-go is failing on container startup

### ISSUE THREAD

**Issue by pasimoes** [oracle/microservices-datadriven#134] opened 2021-06-30 16:33 UTC
The deployment of inventory-go is failing on container startup.

![image](https://user-images.githubusercontent.com/13249199/123998278-b424ab80-d9a7-11eb-9d28-7e818b57dd36.png)

We can see that inventory-go is failing with “CrashLoopBackOff”

![image](https://user-images.githubusercontent.com/13249199/123998340-c9013f00-d9a7-11eb-803e-c79ddde9dca0.png)

**Comment by paulparkinson** [comment] 2021-07-08 01:43
fyi I still couldn't reproduce this issue and test.sh etc passes

**Comment by paulparkinson** [comment] 2021-10-12 20:47
closing as unable to reproduce

**Closed as completed** 2021-10-12 20:47 UTC
Labels: bug
